In [1]:
import numpy as np
x=np.array([2,3,4,5,6])
x

array([2, 3, 4, 5, 6])

In [2]:
np.max(x)

6

In [11]:
x=np.arange(2,200,2)#(starting,ending,size of steps)
x

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100, 102, 104,
       106, 108, 110, 112, 114, 116, 118, 120, 122, 124, 126, 128, 130,
       132, 134, 136, 138, 140, 142, 144, 146, 148, 150, 152, 154, 156,
       158, 160, 162, 164, 166, 168, 170, 172, 174, 176, 178, 180, 182,
       184, 186, 188, 190, 192, 194, 196, 198])

In [12]:
x/2

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25., 26.,
       27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38., 39.,
       40., 41., 42., 43., 44., 45., 46., 47., 48., 49., 50., 51., 52.,
       53., 54., 55., 56., 57., 58., 59., 60., 61., 62., 63., 64., 65.,
       66., 67., 68., 69., 70., 71., 72., 73., 74., 75., 76., 77., 78.,
       79., 80., 81., 82., 83., 84., 85., 86., 87., 88., 89., 90., 91.,
       92., 93., 94., 95., 96., 97., 98., 99.])

In [13]:
x+3

array([  5,   7,   9,  11,  13,  15,  17,  19,  21,  23,  25,  27,  29,
        31,  33,  35,  37,  39,  41,  43,  45,  47,  49,  51,  53,  55,
        57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,  79,  81,
        83,  85,  87,  89,  91,  93,  95,  97,  99, 101, 103, 105, 107,
       109, 111, 113, 115, 117, 119, 121, 123, 125, 127, 129, 131, 133,
       135, 137, 139, 141, 143, 145, 147, 149, 151, 153, 155, 157, 159,
       161, 163, 165, 167, 169, 171, 173, 175, 177, 179, 181, 183, 185,
       187, 189, 191, 193, 195, 197, 199, 201])

In [14]:
x*3

array([  6,  12,  18,  24,  30,  36,  42,  48,  54,  60,  66,  72,  78,
        84,  90,  96, 102, 108, 114, 120, 126, 132, 138, 144, 150, 156,
       162, 168, 174, 180, 186, 192, 198, 204, 210, 216, 222, 228, 234,
       240, 246, 252, 258, 264, 270, 276, 282, 288, 294, 300, 306, 312,
       318, 324, 330, 336, 342, 348, 354, 360, 366, 372, 378, 384, 390,
       396, 402, 408, 414, 420, 426, 432, 438, 444, 450, 456, 462, 468,
       474, 480, 486, 492, 498, 504, 510, 516, 522, 528, 534, 540, 546,
       552, 558, 564, 570, 576, 582, 588, 594])

In [15]:
#we can use airthmetic operators on numpy array but not on python list
#numpy provides rich functionalities.
#numpy is faster than list.

In [18]:
x=np.arange(2,20,2)
print(x)
print("**",x**2)
print("//",x//2)
print("%",x%3)

[ 2  4  6  8 10 12 14 16 18]
** [  4  16  36  64 100 144 196 256 324]
// [1 2 3 4 5 6 7 8 9]
% [2 1 0 2 1 0 2 1 0]


In [20]:
x=np.zeros(6)
x

array([0., 0., 0., 0., 0., 0.])

In [22]:
x=np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [28]:
x=np.ones((3,3),dtype="int")
x

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [26]:
x=np.zeros((10,10))
x

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [114]:
x=np.full((6,6),3.14)
x

array([[3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14, 3.14]])

In [33]:
x=np.full()
x

array([[1, 1],
       [1, 1]])

In [35]:
x=np.eye(5)#gives identity matrix
x

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
x=np.random.random((5,5))#to generate random number matrix b/w 0 and 1
x

array([[0.12283911, 0.98245701, 0.70823784, 0.75108681, 0.92474551],
       [0.81543422, 0.82570757, 0.60943128, 0.93649292, 0.73042709],
       [0.14843902, 0.27605824, 0.58901283, 0.26925225, 0.36653528],
       [0.63031667, 0.6604211 , 0.84629157, 0.08566508, 0.59478417],
       [0.35188512, 0.88170353, 0.45359372, 0.01945588, 0.47002853]])

In [40]:
np.random.seed(2)# to freez the generated numbers at time
x=np.random.random((5,5))
x

array([[0.4359949 , 0.02592623, 0.54966248, 0.43532239, 0.4203678 ],
       [0.33033482, 0.20464863, 0.61927097, 0.29965467, 0.26682728],
       [0.62113383, 0.52914209, 0.13457995, 0.51357812, 0.18443987],
       [0.78533515, 0.85397529, 0.49423684, 0.84656149, 0.07964548],
       [0.50524609, 0.0652865 , 0.42812233, 0.09653092, 0.12715997]])

In [44]:
x=np.random.randint(6,9,(6,6))
x

array([[6, 6, 7, 7, 7, 6],
       [6, 8, 8, 7, 7, 8],
       [7, 8, 6, 8, 7, 6],
       [8, 6, 8, 6, 8, 7],
       [6, 6, 8, 8, 7, 7],
       [7, 8, 7, 8, 6, 7]])

In [48]:
x=np.random.randint(1,10,5)
x

array([3, 6, 2, 4, 4])

In [82]:
x=np.random.randint(10,size=(6,6))
x

array([[5, 5, 3, 9, 1, 8],
       [1, 4, 6, 2, 6, 7],
       [5, 0, 1, 5, 6, 9],
       [8, 8, 2, 6, 0, 6],
       [0, 4, 3, 3, 7, 0],
       [9, 2, 2, 3, 5, 6]])

In [56]:
np.min(x)

0

In [57]:
np.max(x)

9

In [61]:
np.min(x,axis=0) #min values of columns

array([1, 2, 0, 1, 1, 2])

In [63]:
np.min(x,axis=1)#min values of rows


array([1, 1, 1, 0, 1, 0])

In [64]:
np.mean(x)

3.3055555555555554

In [68]:
np.mean(x,axis=1)#mean values of rows

array([4.83333333, 3.        , 2.33333333, 2.33333333, 3.16666667,
       4.16666667])

In [70]:
np.mean(x,axis=0)#mean values of columns

array([2.33333333, 5.16666667, 1.5       , 3.33333333, 2.66666667,
       4.83333333])

In [71]:
np.median(x)

3.0

In [72]:
np.median(x,axis=1)#medians of rows

array([5.5, 2. , 2.5, 2.5, 2.5, 3.5])

In [73]:
np.median(x,axis=0)#median of columns

array([2. , 4.5, 1.5, 3. , 2.5, 6. ])

In [78]:
x=np.arange(2,10,1)
print(x)
print("Sin theta=",np.sin(x))
print("Cos theta=",np.cos(x))
print("Tan theta=",np.tan(x))

[2 3 4 5 6 7 8 9]
Sin theta= [ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155   0.6569866
  0.98935825  0.41211849]
Cos theta= [-0.41614684 -0.9899925  -0.65364362  0.28366219  0.96017029  0.75390225
 -0.14550003 -0.91113026]
Tan theta= [-2.18503986 -0.14254654  1.15782128 -3.38051501 -0.29100619  0.87144798
 -6.79971146 -0.45231566]


In [84]:
x=np.arange(2,10,1)
print(x)
print("log values base e=",np.log(x))
print("log values base 2=",np.log2(x))
print("log values base 10=",np.log10(x))

[2 3 4 5 6 7 8 9]
log values base e= [0.69314718 1.09861229 1.38629436 1.60943791 1.79175947 1.94591015
 2.07944154 2.19722458]
log values base 2= [1.         1.5849625  2.         2.32192809 2.5849625  2.80735492
 3.         3.169925  ]
log values base 10= [0.30103    0.47712125 0.60205999 0.69897    0.77815125 0.84509804
 0.90308999 0.95424251]


In [89]:
x=np.random.randint(2,40,(6,6))
print(x.ndim)
print(x.dtype)
print(x.itemsize)#size of each item
print(x.nbytes)#no of bytes
print(x.size)#no of elements

2
int32
4
144
36


In [91]:
x=np.random.randint(2,50,(5,5))
x

array([[23, 42, 17, 22, 35],
       [35, 14, 20,  9, 43],
       [24, 42, 28, 11, 40],
       [49, 41, 41,  5, 13],
       [31, 45, 31, 29, 48]])

In [99]:
x_sub=x[:2,:2]#to slice subpart of big array
x_sub

array([[99, 42],
       [35, 14]])

In [93]:
x_sub[0,0]=99#to update array element
x_sub

array([[99, 42],
       [35, 14]])

In [95]:
x_sub=x[2:4,2:4]
x_sub

array([[28, 11],
       [41,  5]])

In [97]:
x#updated part in subarray makes the impact on actual array also

array([[99, 42, 17, 22, 35],
       [35, 14, 20,  9, 43],
       [24, 42, 28, 11, 40],
       [49, 41, 41,  5, 13],
       [31, 45, 31, 29, 48]])

In [101]:
#if subarray is just copy of actual array than change in subarray will not impact actual array
x=np.random.randint(2,10,(5,5))
x

array([[4, 2, 4, 5, 6],
       [2, 3, 6, 4, 5],
       [6, 4, 2, 9, 6],
       [4, 4, 7, 7, 7],
       [4, 3, 6, 2, 9]])

In [102]:
x_sub=x[0:2,0:2].copy()
x_sub

array([[4, 2],
       [2, 3]])

In [105]:
x_sub[0,0]=100#updation at first element of subarray
x_sub

array([[100,   2],
       [  2,   3]])

In [106]:
x

array([[4, 2, 4, 5, 6],
       [2, 3, 6, 4, 5],
       [6, 4, 2, 9, 6],
       [4, 4, 7, 7, 7],
       [4, 3, 6, 2, 9]])

In [107]:
grid=[[1,2,3],
      [4,5,6]]
x=np.concatenate([grid,grid],axis=1)
x

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [108]:
#reshape to convert a 1d array into 2d array
x=np.arange(16).reshape(4,4)
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [109]:
np.pi

3.141592653589793

In [111]:
x=np.vstack(([1,2,3],[5,6,7]))
x

array([[1, 2, 3],
       [5, 6, 7]])

In [112]:
x=np.hstack(([1,2,3],[4,5,6]))
x

array([1, 2, 3, 4, 5, 6])

In [116]:
x=np.vstack(([[1,2,3],[4,5,6]],[[5,6,7],[7,8,9]]))
x

array([[1, 2, 3],
       [4, 5, 6],
       [5, 6, 7],
       [7, 8, 9]])

In [ ]:
#in vstack and hstack input/parameter is passed as tuple.